baseURL = 'http://example.org/'
languageCode = 'en-us'
theme = "JuiceBar"
title = "Hotjuice's Blog"

[params]
author = "Hotjuice"
description = "Hotjuice's blog"
# 如果您想在每篇博客文章中显示自己的图像，则将图像添加到static/images目录并修改站点参数config.toml以指向它
authorImage = "/images/profile.jpg"
paginate = 4

Title = "热果汁"
content = "I'm Hotjuice, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/avatar.jpg"
#添加新的社交图标
[[params.social]]
name = "Github"
url = "https://github.com/hotjuicew"
[[params.social]]
name = "telegram"
url = "https://t.me/Hotjuice"
[[params.social]]
name = "twitter"
url = "https://twitter.com/hotjuicee"
[[params.social]]
name = "email"
url = "mailto:hotjuicew@outlook.com"

[taxonomies]
category = "categories"
tag = "tags"

# 添加新的导航链接
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# 添加页脚显示的所有链接
[[menu.footer]]
name = "About"
url = "/about"
[[menu.footer]]
name = "Privacy"
url = "/privacy"



#用于输出文档的设置


[outputs]
home = ["HTML", "RSS", "JSON"]