baseURL = 'http://add1.dev/'
languageCode = 'zh-CN'
paginate = 4
theme = "JuiceBar"
title = "Jasmine's Blog"
[params]
author = "Jasmine"
authorImage = "/images/profile.jpg"
description = "Jasmine's blog"

Title = "Jasmine"
content = "I'm Jasmine, nice to meet you(ˊ˘ˋ*)♡"
imageUrl = "/images/avatar.jpg"
#添加新的社交图标
[[params.social]]
name = "Github"
url = "https://github.com/hotjuicew"
[[params.social]]
name = "telegram"
url = "https://t.me/Hotjuice"
[[params.social]]
name = "email"
url = "mailto:hotjuicew@outlook.com"

[taxonomies]
category = "categories"
tag = "tags"

# 添加新的导航链接
[[menu.main]]
name = "About"
url = "/about"
[[menu.main]]
name = "Blog"
url = "/post"
[[menu.main]]
name = "Categories"
url = "/categories"

# 添加页脚显示的所有链接
[[menu.footer]]
name = "About"
url = "/about"
[[menu.footer]]
name = "Privacy"
url = "/privacy"

[params.giscus]
category = "Announcements"
categoryID = "DIC_kwDOHHQOu84CWCQ3"
emitMetadata = "0"
inputPosition = "bottom"
lang = "en"
loading = "lazy"
mapping = "og:title"
reactionsEnabled = "1"
repo = "hotjuicew/blog"
repoID = "R_kgDOHHQOuw"

#用于输出文档的设置
[outputs]
home = ["HTML", "RSS", "JSON"]
